// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsxdgjvjfjxqtcpfiqwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzeGRnanZqZmp4cXRjcGZpcXdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMDIzNzMsImV4cCI6MjA1NzU3ODM3M30.LKyz84yI1bvCxa6-Q3lPRMTC7Q5BQrFS0k47o55gXUM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);